### ISSUE TITLE
A better website

### ISSUE THREAD

**Issue by lmmake** [LorettaDevs/Loretta#105]
The website lags my entire computer and im unable to actually load anything, the colors are rlly shit consider using gitbook thanks  😛 😛 😛 😛

**Comment by HyperNIt3** [comment]
I agree with this, absolutely dogshit

**Comment by StepBroFurious** [comment]
The site made me vomit, it's so dogshit, I agree with you

**Comment by Gork3m** [comment]
fr bro I've been literally waiting for this feature for like 6 months now but THEY JUST WONT ADD IT
