### ISSUE TITLE
Can you add couple a flags?

### ISSUE THREAD

**Issue by Shadowblitz16** [LorettaDevs/Loretta#121]
**Is your feature request related to a problem? Please describe.**
I am considering on using this for a sandboxed scripting language for my game engine. 
However I come from C# and I find lua really hard to read for a few reasons.
- It does not have static typing
- It uses basic syntax like `if` `then` `end`
- It is 1 based.

**Describe the solution you'd like**
Please add the following flags.
- Require static typing for luau
  Makes lua require luau typing
- C style code blocks using `{` `}`
  instead if `then` `end` `do`
- Default as 0 based index 
  tables start at index 0 instead of 1

**Describe alternatives you've considered**
I have considered angel script but I can't find any ports for C#

**Additional context**
NA

**Comment by GGG-KILLER** [comment]
Sorry, but the objective of our library is to provide parsing support for **existing** Lua flavors/versions which are relevant enough.

Creating new Lua flavors isn't the point of this library nor do we have any plans to make the syntax more C-like, if you want a C-like language you're better off looking for another library unfortunately.
Long term we have plans for people who want strict typing in the future but nothing beyond that nor are we a Lua runtime so there would be no way to even make 0-based indexes as we don't execute Lua code.

**Comment by Shadowblitz16** [comment]
@GGG-KILLER where would I look to implement this myself?

**Comment by GGG-KILLER** [comment]
> @GGG-KILLER where would I look to implement this myself?

You would have to modify the parser itself and also implement an interpreter with a runtime, because all we do is strictly parse the code, we do not have a way to run it at all.
