### ISSUE TITLE
Script class initialization is way too slow

### ISSUE THREAD

**Issue by Fiusen** [LorettaDevs/Loretta#78]
Loretta's Script class initialization of a big script takes way too long:

Time on a 20MB file:

-       Script init: 9s
-       Parse time: 0.9s

How to replicate:

- Have a random script (like allopcodes-5.1.lua) and copy and paste it until ur file gets to ~20MB

```
var scriptParsed = new Script(ImmutableArray.Create(LuaSyntaxTree.ParseText(code)));
var root = Parsed[0].GetRoot();

SyntaxNode node = root.ChildNodes().FirstOrDefault(); // whatever

scriptParsed.GetScope(node) // long wait here
```
![4KIgA2zjVv](https://user-images.githubusercontent.com/41023878/158435196-4a7978c5-dadf-4099-ab18-3ae117aeac9d.png)

**Comment by GGG-KILLER** [comment]
After quite a bit of profiling, this is not gonna be possible without rewriting the entire scoping code.

Most of the code is being spent in unmanaged code which means that most of the time is probably being spent in array resizes.

**Comment by GGG-KILLER** [comment]
Closing this since #32 will fix this indirectly.
